# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

updates:
  - directory: /
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
    package-ecosystem: npm
    schedule:
      interval: weekly

  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly

version: 2
