# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

updates:
  - directory: /
    package-ecosystem: npm
    schedule:
      interval: weekly
version: 2
