// Generated by scripts/generate-reserved-route-segments.mjs. Do not edit manually.
export const RESERVED_TOP_LEVEL_ROUTE_SEGMENTS = [
  "account",
  "callback",
  "fluss",
  "praxisplaner",
  "regeln",
] as const;
