description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: 20.x

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Generate Convex code
      run: pnpm run gen:convex
      shell: bash

    - name: Generate TanStack routes
      run: pnpm run gen:routes
      shell: bash

    - name: Verify generated files
      run: |
        echo "--- Verifying generated files ---"
        echo "Checking for Convex generated files..."
        ls -la convex/_generated/
        test -f convex/_generated/api.js || (echo "ERROR: convex/_generated/api.js not found!" && exit 1)
        echo "Convex files look OK."
        echo "Checking for TanStack Router generated file..."
        ls -la src/
        test -f src/routeTree.gen.ts || (echo "ERROR: src/routeTree.gen.ts not found after generation!" && exit 1)
        echo "src/routeTree.gen.ts found."
        echo "--- Verification complete ---"

      shell: bash
  using: composite
