/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PraxisplanerImport } from './routes/praxisplaner'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PraxisplanerRoute = PraxisplanerImport.update({
  id: '/praxisplaner',
  path: '/praxisplaner',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/praxisplaner': {
      id: '/praxisplaner'
      path: '/praxisplaner'
      fullPath: '/praxisplaner'
      preLoaderRoute: typeof PraxisplanerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/praxisplaner': typeof PraxisplanerRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/praxisplaner': typeof PraxisplanerRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/praxisplaner': typeof PraxisplanerRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/praxisplaner'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/praxisplaner'
  id: '__root__' | '/' | '/praxisplaner'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PraxisplanerRoute: typeof PraxisplanerRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PraxisplanerRoute: PraxisplanerRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/praxisplaner"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/praxisplaner": {
      "filePath": "praxisplaner.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
